version: "3.8"

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_website
    ports:
      - "8080:80" # Map port 8080 on the host to port 80 in the container
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
