version: "3.8"

services:
  backend:
    build:
      context: ./url_shortener_backend
    container_name: url_shortener_backend
    ports:
      - "3000:3000"
    volumes:
      - ./url_shortener_backend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
      NODE_ENV: development

  website:
    build:
      context: ./url_shortener_website
      dockerfile: Dockerfile
    container_name: url_shortener_website
    ports:
      - "8080:80"
    volumes:
      - ./url_shortener_website:/app
    environment:
      - NODE_ENV=development
