version: "3.8"

services:
  backend:
    build:
      context: ./url_shortener_backend
    container_name: url_shortener_backend
    ports:
      - "3000:3000"
    volumes:
      - ./url_shortener_backend:/app  
      - /app/node_modules             
    working_dir: /app
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/url_shortener
      SEED_DB: false
    depends_on:
      - mongo
    command: /bin/bash -c "npm test && npm start" 
    
  website:
    build:
      context: ./url_shortener_website
      dockerfile: Dockerfile
    container_name: url_shortener_website
    ports:
      - "8080:80"
    volumes:
      - ./url_shortener_website:/app  
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 5s

volumes:
  mongo_data:
