version: "3.8"

services:
  backend:
    build:
      context: ./url_shortener_backend
    container_name: url_shortener_backend
    ports:
      - "3000:3000"
    volumes:
      - ./url_shortener_backend:/app  # Mount local backend directory to container
      - /app/node_modules             # Mount node_modules folder to persist dependencies
    working_dir: /app
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/url_shortener
      SEED_DB: false
    depends_on:
      - mongo
    command: /bin/bash -c "npm test && npm start" 
      
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 5s

volumes:
  mongo_data:
